[project]
name = "parking-rental"
authors = []
description = ""
telemetry = false
requirements = []
[contracts.parking-rental]
path = "contracts/parking-rental.clar"
depends_on = []

[contracts.parking-spot]
path = "contracts/parking-spot.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
